### ISSUE TITLE
dev-compose.yml doesn't work on Windows

### ISSUE THREAD

**Issue by Clemy-beep** [unitystation/changelog-api#3]
Hi ! I forked the repository because i wanted to implement the possibility to filter changelog's changes by dates on the website. 

I created the .env file and changed DB_HOST from localhost to 127.0.0.1 but when I run  `docker-compose -f .\dev-compose.yml up`, i get the following error :

`changelog-api-changelog-api-web-1  | django.db.utils.OperationalError: could not connect to server: Connection refused
changelog-api-changelog-api-web-1  |    Is the server running on host "127.0.0.1" and accepting
changelog-api-changelog-api-web-1  |    TCP/IP connections on port 5432?`

When i try to connect to the db from DBeaver, it works though. 

Did i do something wrong ? Is something missing in the dev-compose.yml file ?

Thanks in advance for your repsonse

**Comment by corp-0** [comment]
> localhost to 127.0.0.1

Leaving as localhost should work just fine. 

Now, if all you want to do is to work on the website, you can fetch from the production API and not run central-command locally.

Leave this issue open until I try to run this on windows and confirm if it is working.

**Comment by corp-0** [comment]
Ah, I just remembered what is your issue. If you are running both the Django app and DB using docker, you need to use the container name instead of localhost.

**Comment by Clemy-beep** [comment]
Replacing the  hostname by the container name works, thanks for your fast reponse !
